spring:
  application:
    name: x6-order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/x6_order
    username: test
    password: ${DB_PG_PWD}
server:
  port: ${APP_PORT:8080}
services:
  user-service-url: http://localhost:8081
  product-service-url: http://localhost:8082